### ISSUE TITLE
Remove a redeemed option from My Options list

### ISSUE THREAD

**Issue by remote-gildor** [DeFiOptions/DeFiOptions-frontend#27]
Polygon's RPC node is slow to update state, so it may make sense to remove a redeemed (or sold out) option from My Options programmatically, without waiting for the updated state from a Polygon node.

**Comment by TCGV** [comment]
We could also hide expired options by default since they're worthless (i.e. they have no intrinsic value to redeem):

![image](https://user-images.githubusercontent.com/2445889/142950688-347dfd12-e18d-46ee-b06b-b514296e420a.png)

And maybe we could add a "show expired options" checkbox for allowing users to optinally query them.

**Comment by remote-gildor** [comment]
Agree, I created a new issue for that: https://github.com/DeFiOptions/DeFiOptions-frontend/issues/32
