### ISSUE TITLE
Hide expired options by default, but allow users to toggle the visibility

### ISSUE THREAD

**Issue by remote-gildor** [DeFiOptions/DeFiOptions-frontend#32]
On the portfolio page, hide expired options by default, but allow users to see them via a toggle button.

**Comment by TCGV** [comment]
Maybe I wasn't claer enough on my [original comment](https://github.com/DeFiOptions/DeFiOptions-frontend/issues/27#issuecomment-976009864) but there are two possible situations when dealing with expired options:

1. Non-zero intrinsict value = Users should **redeem** these options for receiving their intrinsict values
2. Zero intrinsict value = Users don't need to redeem these options, **they're worthless**

Currently both of them are being hidden:

![image](https://user-images.githubusercontent.com/2445889/143786676-017151f6-b9c9-4991-bbf7-dbc3f78db83b.png)

When setting the "show expired options" they become visible:

![image](https://user-images.githubusercontent.com/2445889/143786693-32b53238-a2e4-4d52-aafd-af81524982aa.png)

It is important not to hide expired options with **non-zero** intrinsict value by default since users should **redeem** their intrinsict values manually.

**Comment by remote-gildor** [comment]
Ok, done, although I cannot confirm 100% if it works because I don't have any redeemable option on my list - can you check it?

**Comment by TCGV** [comment]
> Ok, done, although I cannot confirm 100% if it works because I don't have any redeemable option on my list - can you check it?

It worked! Thanks G.
